# Generated by Django 4.1.7 on 2023-06-18 18:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('taille', models.PositiveIntegerField()),
                ('nombre_chambres', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Proprietaire',
                'verbose_name_plural': 'Proprietaires',
                'db_table': 'Proprietaire',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'Utilisateur',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appartement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAppartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='appartements/')),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appartement')),
            ],
        ),
        migrations.AddField(
            model_name='appartement',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.proprietaire'),
        ),
    ]
