# Generated by Django 4.1.7 on 2023-06-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='myapp.proprietaire')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reservation')),
            ],
        ),
    ]
