# Generated by Django 4.1.7 on 2023-06-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reservation',
        ),
        migrations.AddField(
            model_name='message',
            name='appartement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.appartement'),
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
