# Generated by Django 4.1.7 on 2023-06-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_message_expediteur_remove_message_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expediteur_phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
