# Generated by Django 4.1.7 on 2023-06-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_message_expediteur_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='expediteur_phone',
        ),
    ]
