# Generated by Django 4.1.7 on 2023-06-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_message_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='phone',
            new_name='expediteur_phone',
        ),
    ]
