# Generated by Django 4.1.7 on 2023-06-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_appartement_profil_photo_proprietaire_profil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='nombre_chambres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='prix',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='taille',
            field=models.CharField(max_length=100),
        ),
    ]
