# Generated by Django 4.2.3 on 2023-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_appartement_nombre_chambres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='garrage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appartement',
            name='salle_de_bain',
            field=models.CharField(default='', max_length=100),
        ),
    ]
