# Generated by Django 4.2.3 on 2023-07-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_appartement_garrage_appartement_salle_de_bain'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
